version: '3'

services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpass'
      MYSQL_DATABASE: 'housetable'
    ports:
      - '3306:3306'
  #   volumes: - mysqldata:/var/lib/mysql
  # volumes:
  #   mysqldata:
